# Generated by Django 6.0 on 2026-01-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
    ]
